apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: akashgajjala10/book-catalog:latest  
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://db_4148_sit722_part2_user:MAxHlVYFT3IstwhGFnWctjCM8wx5yoR5@dpg-cresb9tsvqrc73fmedpg-a.oregon-postgres.render.com/db_4148_sit722_part2"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 80             # External port (can be accessed as http://<node-ip>:80)
      targetPort: 8000     # Target port on the container
      nodePort: 30002      # NodePort (accessible externally)
  type: NodePort